"""empty message

Revision ID: c221b2d3efad
Revises: a4102fada4f7
Create Date: 2017-12-23 22:29:17.515816

"""

# revision identifiers, used by Alembic.
revision = 'c221b2d3efad'
down_revision = 'a4102fada4f7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['homework.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('essay_submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('essay_submission')
    op.drop_table('essay')
    # ### end Alembic commands ###
